name: Test & Deploy

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - run: exit 0
  test-windows:
    runs-on: ubuntu-18.04
    steps:
    - run: exit 0
  test-macos:
    runs-on: ubuntu-18.04
    steps:
    - run: exit 0
  
  build-windows:
    needs: [test-ubuntu, test-windows, test-macos]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: .travis/install-windows.sh
      shell: bash
    - name: Build & Test
      run: .travis/build-windows.sh release
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-exe
        path: build/bin/RelWithDebInfo/solvespace.exe

  build-windows-openmp:
    needs: [test-ubuntu, test-windows, test-macos]
    name: Windows with OpenMP
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: .travis/install-windows.sh
      shell: bash
    - name: Build & Test
      run: .travis/build-windows.sh release openmp
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-openmp-exe
        path: build/bin/RelWithDebInfo/solvespace-openmp.exe

  # test-ubuntu:
  #     runs-on: ubuntu-18.04
  #     steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Dependencies
  #       run: .travis/install-ubuntu.sh
  #     - name: Build & Test
  #       run: .travis/build-ubuntu.sh

  # test-windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Add msbuild to PATH
  #     uses: microsoft/setup-msbuild@v1.0.2
  #   - name: Install Dependencies
  #     run: .travis/install-windows.sh
  #   - name: Build & Test
  #     run: .travis/build-windows.sh
  #     shell: bash

  # test-macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install Dependencies
  #     run: .travis/install-macos.sh
  #   - name: Build & Test
  #     run: .travis/build-macos.sh
